### ISSUE TITLE
Error message when leaving a game

### ISSUE THREAD

**Issue by kokolegorille** [ventsislaf/talks#1]
Hello, nice work...
But I've got an error message when a game is terminated.
eg. 
Connect
Create new game
Then return to homepage

Because it's the last player of the game, game will terminate when channel terminate.

Every thing is fine, channel stop, calls Game.leave, as there is no more player, close the game.
Except that anoying error message

Here is the log:

[error] GenServer #PID<0.454.0> terminating
** (stop) exited in: GenServer.call(#PID<0.455.0>, {:leave, :x}, 5000)
    ** (EXIT) normal
    (elixir) lib/gen_server.ex:604: GenServer.call/3
    (demo) web/channels/game_channel.ex:48: Demo.GameChannel.terminate/2
    (stdlib) gen_server.erl:629: :gen_server.try_terminate/3
    (stdlib) gen_server.erl:795: :gen_server.terminate/7
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :close}
State: %Phoenix.Socket{assigns: %{game: "kiki", player: "kiki", symbol: :x}, channel: Demo.GameChannel, channel_pid: #PID<0.454.0>, endpoint: Demo.Endpoint, handler: Demo.UserSocket, id: nil, joined: true, pubsub_server: Demo.PubSub, ref: nil, serializer: Phoenix.Transports.WebSocketSerializer, topic: "game:kiki", transport: Phoenix.Transports.WebSocket, transport_name: :websocket, transport_pid: #PID<0.452.0>}

**Comment by cjen07** [comment]
I solved it by changing `{:stop, :normal, new_state}` to `{:stop, :normal, new_state, new_state}` in `handle_call({:leave, symbol}, _from, state)` in `game.ex`

**Comment by kokolegorille** [comment]
Thank You for the answer, it works smooth now

2017-02-23 15:37 GMT+01:00 Wang Chen <notifications@github.com>:
